version: '3.8'

services:
  # Next.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # AI API Keys (add your keys here or use .env file)
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      
      # Service URLs
      - VNC_BROWSER_SERVICE_URL=http://vnc-browser:8003
      - BROWSER_USE_API_KEY=${BROWSER_USE_API_KEY}
      
      # Storage
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      
      # Other services
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - WAVESPEED_API_KEY=${WAVESPEED_API_KEY}
      
    depends_on:
      - vnc-browser
    networks:
      - app-network
    volumes:
      - ./public:/app/public:ro
      - nextjs-cache:/app/.next/cache
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # VNC Browser Service
  vnc-browser:
    build:
      context: ./browser-agent
      dockerfile: Dockerfile.vnc
    ports:
      - "5900:5900"   # VNC port
      - "6080:6080"   # noVNC web port
      - "8003:8003"   # API port
    environment:
      - DISPLAY=:99
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - /dev/shm:/dev/shm  # Shared memory for Chrome
    privileged: true  # Required for some browser operations
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/api/vnc-browser/sessions"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  app-network:
    driver: bridge

volumes:
  nextjs-cache: