version: '3.8'

services:
  # Browser Agent Service (Python)
  browser-agent:
    build:
      context: ./browser-agent
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./browser-agent:/app
    restart: unless-stopped
    networks:
      - app-network

  # Optional: Run the existing WebSocket server if needed
  browser-ws:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run browser:ws
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - browser-agent

networks:
  app-network:
    driver: bridge
